/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author CPU
 */
public class Frm_PanelStaff extends javax.swing.JFrame {

    /**
     * Creates new form Frm_PanelStaff
     */
    public Frm_PanelStaff() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbtn_addEmpleado = new javax.swing.JButton();
        jbtn_deleteEmpleado = new javax.swing.JButton();
        jbtn_editEmpleado = new javax.swing.JButton();
        jbtn_addMascota = new javax.swing.JButton();
        jbtn_deleteMascota = new javax.swing.JButton();
        jbtn_retroceder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Panel Staff");

        jPanel1.setBackground(new java.awt.Color(240, 246, 150));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Panel Staff");
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel1.setOpaque(true);

        jbtn_addEmpleado.setText("Agregar Empleado");
        jbtn_addEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_addEmpleadoActionPerformed(evt);
            }
        });

        jbtn_deleteEmpleado.setText("Eliminar Empleado");
        jbtn_deleteEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_deleteEmpleadoActionPerformed(evt);
            }
        });

        jbtn_editEmpleado.setText("Editar Empleado");
        jbtn_editEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_editEmpleadoActionPerformed(evt);
            }
        });

        jbtn_addMascota.setText("Agregar Mascota");
        jbtn_addMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_addMascotaActionPerformed(evt);
            }
        });

        jbtn_deleteMascota.setText("Eliminar Mascota");
        jbtn_deleteMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_deleteMascotaActionPerformed(evt);
            }
        });

        jbtn_retroceder.setBackground(new java.awt.Color(248, 229, 84));
        jbtn_retroceder.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jbtn_retroceder.setText("Retroceder");
        jbtn_retroceder.setBorder(new javax.swing.border.MatteBorder(null));
        jbtn_retroceder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_retroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_retrocederActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jbtn_retroceder, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtn_addEmpleado)
                        .addGap(73, 73, 73)
                        .addComponent(jbtn_deleteEmpleado)
                        .addGap(73, 73, 73)
                        .addComponent(jbtn_editEmpleado)
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtn_addMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jbtn_deleteMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(186, 186, 186))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbtn_retroceder, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(128, 128, 128)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_addEmpleado)
                    .addComponent(jbtn_deleteEmpleado)
                    .addComponent(jbtn_editEmpleado))
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_addMascota)
                    .addComponent(jbtn_deleteMascota))
                .addContainerGap(306, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_addEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_addEmpleadoActionPerformed
        
        Frm_AgregarEmpleado agregarEmpleado = new Frm_AgregarEmpleado();
        agregarEmpleado.setVisible(true);
        
    }//GEN-LAST:event_jbtn_addEmpleadoActionPerformed

    private void jbtn_deleteEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_deleteEmpleadoActionPerformed
        
        Frm_EliminarEmpleado panel = new Frm_EliminarEmpleado();
        panel.setVisible(true);

    }//GEN-LAST:event_jbtn_deleteEmpleadoActionPerformed

    private void jbtn_editEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_editEmpleadoActionPerformed
        
        Frm_EditarEmpleado panel = new Frm_EditarEmpleado();
        panel.setVisible(true);
        
    }//GEN-LAST:event_jbtn_editEmpleadoActionPerformed

    private void jbtn_deleteMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_deleteMascotaActionPerformed
        
        Frm_EliminarMascota panel = new Frm_EliminarMascota();
        panel.setVisible(true);
        
    }//GEN-LAST:event_jbtn_deleteMascotaActionPerformed

    private void jbtn_retrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_retrocederActionPerformed
        dispose();
    }//GEN-LAST:event_jbtn_retrocederActionPerformed

    private void jbtn_addMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_addMascotaActionPerformed
        
        Frm_AgregarMascota agregarMascota = new Frm_AgregarMascota();
        agregarMascota.setVisible(true);
        
    }//GEN-LAST:event_jbtn_addMascotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_PanelStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_PanelStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_PanelStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_PanelStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_PanelStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtn_addEmpleado;
    private javax.swing.JButton jbtn_addMascota;
    private javax.swing.JButton jbtn_deleteEmpleado;
    private javax.swing.JButton jbtn_deleteMascota;
    private javax.swing.JButton jbtn_editEmpleado;
    private javax.swing.JButton jbtn_retroceder;
    // End of variables declaration//GEN-END:variables
}
